### ISSUE TITLE
GetRootUrl method issue in Load balancer environment

### ISSUE THREAD

**Issue by javafun** [benmccallum/CoreWeb#1]
We had issue for the payment notification postback due to the root URL does generate http instead https. 

I would recommend to follow the article below and fix the issue for the load balancer environment. 
http://www.bugdebugzone.com/2013/12/identifying-https-or-ssl-connection-in.html 

Thanks
Vincent

**Comment by benmccallum** [comment]
Hey Vincent, Hope it's all going well back there. The issue is that if you follow that post and use headers to identify SSL but your site isn't behind a load balancer you'd open yourself up to someone spoofing they were over https right? I'm not sure if that's a bad thing but it is a little worrying. What do you reckon?

**Comment by benmccallum** [comment]
I mean I've used that approach before many times but never from my library. I guess I could create an overload that says "isBehindSslTermination" or something so it knows to check the header

**Comment by javafun** [comment]
Hey Ben, thank you for your prompt reply. I hope everything is going well with you and you enjoy your trip. 

Back to this issue, If someone spoofing header to make request become https, I feel that he fool himself, isn't it? how can someone steal the info via https, :p: HAHA

**Comment by benmccallum** [comment]
Trip is going well mate. Hmm, I'm just thinking, could someone do a man-in-the-middle CSRF attack? A hidden form that POSTs to your site and then includes this header so that the response data is revealed unecryptes for them to steal?
